version: '3'
services:
    proxy:
        image: traefik
        labels:
            com.github.aegypius.mkcert-for-nginx-proxy.docker_gen: ''
        volumes:
            - ./traefik.yaml:/etc/traefik/traefik.yaml
            - ./conf/traefik:/etc/traefik/dynamic
            - letsencrypt-acme:/letsencrypt
            - ssl-certs:/etc/cert
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - 0.0.0.0:80:80
            - 0.0.0.0:443:443
            - 0.0.0.0:8080:8080
        networks:
            - proxy
        restart: unless-stopped
        container_name: proxy
        healthcheck:
            test: traefik healthcheck --ping
    mkcert:
        image: rogerdz/mkcert
        volumes:
            - ssl-certs:/app/certs:rw
            - ~/.mozilla/firefox:/root/.mozilla/firefox:rw
            - ~/.pki/nssdb:/root/.pki/nssdb:rw
            - ~/.local/share/mkcert:/app/ca:rw
            - ${CA_STORE:-/usr/local/share/ca-certificates}:/usr/local/share/ca-certificates
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - proxy
        restart: unless-stopped
        container_name: mkcert
    hosts:
        image: rogerdz/hosts-local
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/hosts:/hosts
            - hosts-local:/config
        networks:
            - proxy
        init: true
        restart: unless-stopped
        container_name: hosts
    adminer:
        image: adminer
        command: php -S 0.0.0.0:8080 -t /var/www/html
        environment:
            ADMINER_PLUGINS: tables-filter json-column table-indexes-structure
        ports:
          - 0.0.0.0:81:8080
        networks:
            - database
        restart: unless-stopped
        container_name: adminer
    maildev:
        image: dominikserafin/maildev
        command: --mail-directory /var/maildev/data
        volumes:
            - mail-data:/var/maildev/data
        ports:
            - 0.0.0.0:82:1080
        networks:
            - mail
        restart: unless-stopped
        container_name: maildev
    # elasticsearch-hq:
    #     image: elastichq/elasticsearch-hq
    #     environment:
    #         HQ_DEFAULT_URL: http://elasticsearch:9200
    #     ports:
    #         - 0.0.0.0:83:5000
    #     networks:
    #         - esnet
    #     init: true
    #     restart: unless-stopped
    #     container_name: elasticsearch-hq
networks:
    proxy:
        driver: bridge
        name: proxy
    database:
        driver: bridge
        name: database
    mail:
        driver: bridge
        name: mail
    esnet:
        driver: bridge
        name: esnet
volumes:
    letsencrypt-acme:
    hosts-local:
    ssl-certs:
        name: ssl-certs
    mail-data:
