global:
    checkNewVersion: false
    sendAnonymousUsage: false

api:
    insecure: true
    dashboard: true
    # debug: true

ping: {}

# log:
#     level: DEBUG

entryPoints:
    http:
        address: ":80"
    https:
        address: ":443"

providers:
    docker:
        network: proxy
        exposedByDefault: false
    file:
        directory: "/etc/traefik/dynamic"
        watch: true

certificatesResolvers:
    letsencrypt:
        acme:
            caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
            email: "webmaster@gmail.com"
            storage: letsencrypt/acme.json
            httpChallenge:
                entryPoint: http